"""Prompt construction shared by all evaluation families."""

from __future__ import annotations

from .data import Episode


SCENE_TEMPLATE = """Below is a description of the \"{task_name}\" task.

Task description:
{task_description}

Observation space:
{observation_space}

Action space:
{action_space}

Reward space:
{reward_space}

Transition dynamics:
{transition_dynamics}

Initial state:
{init_state}

Termination:
{termination}
"""


def system_prompt(task: object) -> str:
    return SCENE_TEMPLATE.format(**task.data).strip()


def user_prompt(
    episode: Episode,
    *,
    history_start: int,
    history_end: int,
    indexed_history: bool,
    drop_last_state_feature: bool,
    question: str,
) -> str:
    history = episode.history_text(
        history_start,
        history_end,
        indexed=indexed_history,
        drop_last_state_feature=drop_last_state_feature,
    )
    return (
        "Given the following snippet of an episode generated by a trained reinforcement-learning "
        "agent:\n\n"
        f"{history}\n\n"
        "Analyze the sequence to answer this question:\n"
        f"{question.strip()}"
    )
